# Generated by Django 5.0.3 on 2024-08-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_shopdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
