# Generated by Django 5.0.3 on 2024-09-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_service_email_service_phone_service_serv_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='shop',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
