# Generated by Django 5.0.3 on 2024-09-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_service_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetails',
            name='lnumber',
            field=models.CharField(max_length=20),
        ),
    ]
