# Generated by Django 5.0.3 on 2024-08-21 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=100)),
                ('lnumber', models.IntegerField()),
                ('palce', models.CharField(max_length=50)),
                ('istate', models.CharField(max_length=50)),
                ('idate', models.DateField()),
                ('edate', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.register')),
            ],
        ),
    ]
