# Generated by Django 5.0.3 on 2024-08-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_shopdetails_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopdetails',
            old_name='palce',
            new_name='place',
        ),
    ]
