# Generated by Django 5.0.3 on 2024-09-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_alter_shopdetails_lnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='issue',
            field=models.CharField(max_length=20),
        ),
    ]
