# Generated by Django 5.0.3 on 2024-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='rating',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
