# Generated by Django 5.0.3 on 2024-10-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0015_complaint_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
