# Generated by Django 5.0.3 on 2024-10-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0017_booking_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='issue',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(max_length=50),
        ),
    ]
