# Generated by Django 5.0.3 on 2024-10-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0018_alter_booking_issue_alter_booking_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='worker',
            field=models.CharField(max_length=20),
        ),
    ]
