# Generated by Django 5.0.3 on 2024-10-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0021_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
