# Generated by Django 5.0.3 on 2024-10-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0022_worker_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vehiclenum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
