# Generated by Django 5.0.3 on 2024-10-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0023_service_vehiclenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaintwoker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=10)),
                ('mechanic', models.CharField(max_length=20)),
                ('issue', models.CharField(max_length=20)),
            ],
        ),
    ]
