# Generated by Django 5.0.3 on 2024-10-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0024_complaintwoker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='vehiclenum',
            field=models.CharField(max_length=20),
        ),
    ]
