# Generated by Django 5.0.3 on 2024-10-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0026_rename_state_worker_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='location',
            new_name='state',
        ),
    ]
