# Generated by Django 5.0.3 on 2024-10-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0027_rename_location_worker_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='location',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
